"""empty message

Revision ID: d8b455cc3f7d
Revises: d0cfadcf06a4
Create Date: 2020-04-25 02:08:58.581047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b455cc3f7d'
down_revision = 'd0cfadcf06a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
